### ISSUE TITLE
Embedding certificates into Docker images

### ISSUE THREAD

**Issue by xBlaz3kx** [CuAuPro/alpr-system#1]
Embedding certificates into the images might be a potential security risk, as if someone got access to the image itself, he would be able to get private certs from the image. 

Also, if you want to scale the system, no client/device (AI or GPIO handler) should have same certificates.

**Comment by CuAuPro** [comment]
I agree, thank you for that!

Regarding client certificates: Each client has its own certificate, which can be generated with the `mqtt-cryptogen` tool as mentioned in `databus/README`. Do you agree or am I missing something? Otherwise, I will close Issue.

**Comment by xBlaz3kx** [comment]
Regarding the client certificates - yes, I know that the tool will generate the certificates for each client (AI engine and GPIO Handler). 

But, if you want to distribute the Docker image, or if you want to create a scalable deployment (multiple Jetson Nanos that will be connected to an MQTT broker), each Jetson nano should have unique client certificates. Embedding the certificates in the Docker image would mean two Jetson nanos would have the same clients (certificates), when in reality, they would be completely different. Revoking one certificate means both would be unable to communicate with the broker. 

Hopefully that clears my rationale behind not embedding any certificates in the image.

**Comment by CuAuPro** [comment]
I agree! Thank you for that, I will merge with your PR.
