### ISSUE TITLE
Building & pushing Docker images

### ISSUE THREAD

**Issue by xBlaz3kx** [CuAuPro/alpr-system#4]
I suggest creating a pipeline for building and pushing the Docker images to DockerHub, as this would make the deployment of the solution easier. Building locally everytime is both tedious and time consuming.

**Comment by CuAuPro** [comment]
Good idea, I will do that as soon as possible.

**Comment by xBlaz3kx** [comment]
I can prepare the CI pipeline for you in a separate PR. The only thing you'll need to do is choose, where you want to push the images to (e.g. Docker Hub) and configure the credentials in the repository secrets.
